### ISSUE TITLE
No License!?

### ISSUE THREAD

**Issue by davecom** [JackBCousineau/swift-chess#1]
In particular I'm interested in reusing the chess piece graphics and I'm interested where they're from/what license they're under.

**Comment by JackBCousineau** [comment]
My apologies for the late reply! I found all of the images in pychess. There are a bunch under the "Pieces" folder in [this](http://www.pychess.org/download/pychess-0.12rc2.tar.gz) source, which I found on [this](http://chess.stackexchange.com/questions/6272/chess-set-icons) StackExchange thread.

**Comment by davecom** [comment]
Thanks for the reply.  Just an FYI your project should include a LICENSE file spelling out its license and if you reuse resources from other places you need to acknowledge that and also follow the guidelines of their licenses as well.  For instance pychess is licensed under the GPL.  I don't know if that applies to the images too (it probably does) but it means you would also have to release your software under the GPL...

**Comment by JackBCousineau** [comment]
Yes, I'll definitely include actual licensing information and credit attribution in my next commit, along with much more documentation, et al.

This whole thing is just a little side project that I haphazardly uploaded without much thought on a random afternoon, and I frankly didn't expect it'd get any attention at all. Can I ask how you found it?

Regardless, I had always planned on giving this whole thing a liberal open-source license, I just hadn't gotten to it when I made the first push. Thanks for your interest and helpful suggestions!

**Comment by davecom** [comment]
It was mentioned in the last release of SwiftSandbox.io

**Comment by JackBCousineau** [comment]
Oh awesome, I feel so special :) Thanks for the info!
